# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_auto_20240412_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helptext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
