# Generated by Django 2.2.13 on 2020-07-30 10:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localita', '0002_auto_20250408_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
                ('regione', models.CharField(max_length=255)),
                ('latitude',models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
