# Generated by Django 2.2.13 on 2020-07-30 10:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.TextField()),
                ('email', models.TextField()),
                ('telefono', models.TextField(blank=True,null=True)),
                ('messaggio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
