# Generated by Django 3.2.23 on 2025-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('messaggio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contatti',
        ),
    ]
