# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models
from localita.models import Localita

class Migration(migrations.Migration):

    dependencies = [
        #('localita', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='localita',
            field= models.ForeignKey(Localita, on_delete=models.CASCADE, related_name='localita_projects',null=True, blank=True),
        ),
    ]
