# Generated by Django 3.2.23 on 2024-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20240412_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='media/images/'),
        )
    ]
