# Generated by Django 3.2.23 on 2025-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20250402_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
