# Generated by Django 3.2.23 on 2025-07-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_el',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_et',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_hu',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_lt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_nl',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_pt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_el',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_et',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_lt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='name_sv',
        ),
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
