# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models
from projects.models import Localita,Project

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_auto_20250125_1406'),
        ('organisations', '0016_auto_20250125_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
                ('latitude',models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
