# Generated by Django 3.2.23 on 2025-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localita', '0002_auto_20250408_0840'),
        ('projects', '0101_auto_20250125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='localita',
            field= models.ForeignKey('localita.Localita', on_delete=models.CASCADE, related_name='localita_localita',null=True, blank=True),
        ),
    ]
