# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models
from projects.models import Localita,Project

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_auto_20250404_1407')
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='localita',
            field= models.ForeignKey('projects.Localita', on_delete=models.CASCADE, related_name='localita_projects',null=True, blank=True),
        ),
        # migrations.AddField(
        #     model_name='organisation',
        #     name='localita',
        #     field=models.ForeignKey('projects.Localita', on_delete=models.CASCADE, related_name='localita_organisation', null=True,
        #                             blank=True),
        # ),
    ]
