# Generated by Django 3.2.23 on 2025-04-08 08:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('provincia', '0001_initial'),
        ('projects', '0103_project_logo_20250416'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='provincia',
            field= models.ForeignKey('provincia.Province', on_delete=models.CASCADE, related_name='provincia_provincia',null=True, blank=True),
        ),
    ]
