# Generated by Django 3.2.23 on 2024-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('projects', '0104_project_provincia'),
        ('projects', '0103_project_logo_20250416'),
    ]

    operations = [

        migrations.AddField(
            model_name='topic',
            name='concept',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='broader',
            field=models.TextField(null=True),
        ),
    ]
