# Generated by Django 3.2.23 on 2025-07-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localita', '0002_auto_20250408_0840'),
        ('projects', '0106_auto_20250721_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(editable=False, max_length=100)),
                ('sigla', models.CharField(editable=False, max_length=3)),
                ('regione', models.CharField(editable=False, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='localita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localita.localita'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='broader',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='concept',
            field=models.TextField(),
        ),
    ]
