# Generated by Django 3.2.23 on 2025-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_auto_20250722_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='provincia',
            field=models.ManyToManyField(to='projects.Provincia'),
        ),
    ]
