# Generated by Django 3.2.23 on 2025-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_project_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='broader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='concept',
            field=models.TextField(blank=True, null=True),
        ),
    ]
