# Generated by Django 3.2.23 on 2025-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0110_auto_20250725_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
