# Generated by Django 3.2.23 on 2025-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inaturalist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
