# Generated by Django 3.2.23 on 2025-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_project_inaturalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='risultati',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tipo_pubblico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tipo_pubblico_altro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
