# Generated by Django 3.2.23 on 2025-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_auto_20250728_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aree',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(choices=[('not_started', 'Not yet started'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=100),
        ),
    ]
