# Generated by Django 3.2.23 on 2025-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_auto_20250825_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bsw',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
