# Generated by Django 3.2.23 on 2025-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20250721_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language_other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
