# Generated by Django 3.2.23 on 2025-10-22 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20251019_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 9, 16, 31, 97012)),
        ),
    ]
