# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20240803_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
