# Generated by Django 3.2.4 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_interestarea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Type'),
        ),
    ]
