# Generated by Django 3.2.23 on 2025-04-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20250219_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileType',
        ),
    ]
