# Generated by Django 3.2.23 on 2025-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localita',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
