# Generated by Django 3.2.23 on 2025-04-08 08:40

from django.db import migrations, models
from localita.models import Localita


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_auto_20250125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='localita',
            field=models.ForeignKey('localita.Localita', on_delete=models.CASCADE, related_name='localita_localita', null=True,blank=True),
        ),
    ]
