# Generated by Django 3.2.23 on 2025-01-25 14:06

from django.db import migrations, models
from projects.models import Localita

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_auto_20250404_1408')
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='localita',
            field=models.ForeignKey('projects.Localita', on_delete=models.CASCADE, related_name='localita_organisation', null=True,
                                    blank=True),
        ),
    ]
