# Generated by Django 3.2.23 on 2025-04-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_auto_20250125_1406'),
        ('organisations', '0017_auto_20250404_1408'),
    ]

    operations = [
    ]
