# Generated by Django 3.2.23 on 2025-04-08 08:40

from django.db import migrations, models
from localita.models import Localita


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_auto_20250408_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image1',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='image1Credit',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
